services:
  admin:
    build:
      context: "."
      dockerfile: "./admin.Dockerfile"
    image: "sandeshhd/proctorx-frontend-admin:latest"
    ports: 
      - 4200:4200
  students:
    build:
      context: "."
      dockerfile: "./students.Dockerfile"   
    image: "sandeshhd/proctorx-frontend-students:latest"
    ports: 
      - 4300:4200
  super-admin:
    build:
      context: "."
      dockerfile: "./superAdmin.Dockerfile"
    image: "sandeshhd/proctorx-frontend-super-admin:latest"
    ports: 
      - 4400:4200 
  sonarqube:
    image: sonarqube
    ports:
      - "9000:9000"
    networks:
      - sonarnet
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: admin
    volumes:
      - sonarqube_conf:/opt/sonarqube/conf
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
  db:
    image: postgres
    networks:
      - sonarnet
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=admin
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data


networks:
  sonarnet:
    driver: bridge

volumes:
  sonarqube_conf:
  sonarqube_data:
  sonarqube_extensions:
  postgresql:
  postgresql_data: