from seleniumbase import BaseCase
BaseCase.main(__name__, __file__)


class RecorderTest(BaseCase):
    def test_recording(self):
        self.open("http://18.235.13.128:32595/")
        self.open_if_not_url("http://18.235.13.128:32595/auth")
        self.type("div.router-container form input", "admin")
        self.type("div.router-container form div:nth-of-type(2) input", "admin")
        self.click('button:contains("SIGN IN")')
        self.click('a[href="/questions"]')
        self.click('a[href="/view-students"] div')
        self.click('div[aria-label="dropdown trigger"]')
        self.click('li[aria-label="Computer Science and Design"]')
        self.click('p-dropdown[placeholder="Semester"] div:nth-of-type(2) span')
        self.click("ul#pr_id_24_list p-dropdownitem:nth-of-type(2) li")
        self.click('span:contains("Status")')
        self.click('span:contains("Inactive")')
        self.click('span:contains("Inactive")')
        self.click('li[aria-label="Active"]')
        self.click('input[placeholder="Search"]')
        self.click('div[aria-label="dropdown trigger"]')
        self.click('li[aria-label="All"]')
        self.type('input[placeholder="Search"]', "Ak")
        self.click("span.p-tag-value")
        self.click('span:contains("Active")')
        self.click('li[aria-label="Inactive"]')
        self.click("span.p-tag-value")
        self.click('a[href="/faculties"]')
        self.click("table#pr_id_34-table tbody tr td:nth-of-type(6) p-tag span span")
        self.click('a[href="/topics"]')
        self.click('a[href="/branches"]')
        self.click('a:contains("Logout")')
