apiVersion: v1
kind: Service
metadata:
  name: frontend-admin-service
spec:
  selector:
    app: proctorx-frontend-admin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4200
    nodePort: 30001
    name: admin
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-students-service
spec:
  selector:
    app: proctorx-frontend-students
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4200
    nodePort: 30000
    name: students
  type: LoadBalancer

---
apiVersion: v1
kind: Service
metadata:
  name: frontend-super-admin-service
spec:
  selector:
    app: proctorx-frontend-super-admin
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4200
    nodePort: 30002
    name: super-admin
  type: LoadBalancer

